### PR TITLE
fix(proto): Don't close paths from previous HP round we're still interested in

### LINKED ISSUE #337: Current quinn main causes two unit test failures in `iroh` main
The test failures:

```
────────────
     Summary [   8.684s] 82 tests run: 80 passed, 2 failed, 0 skipped
        FAIL [   1.466s] iroh endpoint::connection::tests::test_paths_watcher
        FAIL [   5.386s] iroh endpoint::tests::endpoint_two_direct_add_relay
error: test run failed
```

### PR DESCRIPTION
**Pull request by matheus23**
## Description

We introduced some regressions in iroh main unit tests because we're getting stuck in a loop opening paths and closing them before they finish validating.

This adds a check to make sure we don't close paths from the last holepunching round that we're still interested in.

Fixes #337 

Also:
- Adds logs for some interesting events like when a path is abandoned.
- Changed 4-tuple logs from using src/dst to local/remote as discussed in https://github.com/n0-computer/quinn/pull/331/files#r2699312131
- Print a warning if closing an idle path fails updated the error code for that. This should now match the behavior on other paths.

## Notes & open questions

The `to_canonical` calls are somewhat annoying.
I wish we would clean up all of the IP addr canonicalization a bit. But I'd prefer to fix this bug first, then clean up? [Filed an issue](https://github.com/n0-computer/quinn/issues/342).

---

We should probably clear some timers in `close_path`, because otherwise we might trigger path timers that shouldn't trigger anymore. For some reason if I clear the `PathOpen` timer in `close_path` some tests fail?

### CODE REVIEW

File: quinn-proto/src/connection/mod.rs [hunk 1]
```diff
@@ -1966,8 +1967,13 @@ impl Connection {
...
                     match timer {
                         PathTimer::PathIdle => {
-                            self.close_path(now, path_id, TransportErrorCode::NO_ERROR.into())
-                                .ok();
+                            if let Err(err) = self.close_path(
+                                now,
+                                path_id,
+                                TransportErrorCode::PATH_UNSTABLE_OR_POOR.into(),
+                            ) {
+                                warn!(?err, "failed closing path");
```
Comment (flub) [inline quinn-proto/src/connection/mod.rs:1991]: This is interesting, one reason this can fail is because it might be the last open path. E.g. you could set a path idle timeout without setting a connection idle timeout and then you'd hit this condition without ever giving up on the connection.

I think the spec allows instead to close the connection in this case. Which maybe we should consider here?

Though I appreciate that is outside of the scope of this PR and maybe we should create an issue for it instead.

File: quinn-proto/src/connection/mod.rs [hunk 2]
```diff
@@ -6253,14 +6259,23 @@ impl Connection {
...
+            let ip = path.network_path.remote.ip();
+            let port = path.network_path.remote.port();
+
+            // We only close paths that aren't validated (thus are working) that we opened
+            // in a previous round.
+            // And we only close paths that we don't want to probe anyways.
+            if !addresses_to_probe
+                .iter()
+                .any(|(_, (probe_ip, probe_port))| {
+                    *probe_port == port && probe_ip.to_canonical() == ip.to_canonical()
```
Comment (flub) [inline quinn-proto/src/connection/mod.rs:6290]: The to_cannoical here is suspicious. None of these addresses come directly from the user, so they should already have been converted to either a uniform IPv4 or a uniform IPv6 and be comparable without canonicalisation. So the bug is somewhere else I think and this should not have to do this.

File: quinn-proto/src/connection/mod.rs [hunk 3]
```diff
@@ -6253,14 +6259,23 @@ impl Connection {
...
-            if !validated {
+            let Some(path) = self.path(path_id) else {
+                continue;
+            };
+            let ip = path.network_path.remote.ip();
+            let port = path.network_path.remote.port();
+
+            // We only close paths that aren't validated (thus are working) that we opened
+            // in a previous round.
+            // And we only close paths that we don't want to probe anyways.
```
Comment (flub) [inline quinn-proto/src/connection/mod.rs:6286]: I believe you also need to exclude already abandoned paths for which we have not yet discarded the path state.

**Review by flub — CHANGES_REQUESTED** [review]
Another concern I have about this approach is that the new round is effectively carrying on the in-progress holepunching and not starting anew. By which I mean that if you're already on say attempt number 3 of sending a PATH_CHALLENGE you won't send one again. Which is not exactly what I would expect.

Perhaps the `PathOpen` should be extended when a new round is started if we take this approach?

Have you looked at doing the "debouncing" in iroh instead? I feel like it is using this API wrongly.

File: quinn-proto/src/connection/mod.rs (hunk 2 above)
Comment (matheus23) [reply quinn-proto/src/connection/mod.rs:6290]: I have an issue about canonicalization: #342 

The canonicalization happens *after* this code runs. Below this loop this code tries to figure out `ipv6`, and then does the canonicalization inside a method call (this info is all listed in the issue).

File: quinn-proto/src/connection/mod.rs (hunk 3 above)
Comment (divagant-martian) [reply quinn-proto/src/connection/mod.rs:6286]: closing the path should handle that, don't you think?

File: quinn-proto/src/connection/mod.rs (hunk 2 above)
Comment (flub) [reply quinn-proto/src/connection/mod.rs:6290]: That issue is a much more generic refactor though. We currently already work on a basis that all addresses inside quinn-proto are either all IPv6 or IPv4 only. Here they come from somewhere else in our system and are not in the right format, so we did not enforce this correctly where we received the address. Working around it here will only make things more confusing as we end up with this being strewn all around the place and it will be really hard to tell what is correct after a very short while.

I appreciate that was a prior mistake, but also think fixing it is part of this bugfix.

Comment (divagant-martian) [reply quinn-proto/src/connection/mod.rs:6290]: can we merge as is? This won't be solved here and seems relatively aligned with the current behaviour

**Review by divagant-martian — DISMISSED** [review]

File: quinn-proto/src/connection/mod.rs (hunk 3 above)
Comment (matheus23) [reply quinn-proto/src/connection/mod.rs:6286]: No I think flub is right, we need to check `!self.abandoned_paths.contains(&path_id)` here. Otherwise I might skip paths that were just very recently abandoned, but haven't fully closed yet, where it'd be nice to re-holepunch them if we want to do another attempt.

File: quinn-proto/src/connection/mod.rs (hunk 2 above)
Comment (matheus23) [reply quinn-proto/src/connection/mod.rs:6290]: I turned your suggestion/concern into another PR, if that's okay? https://github.com/n0-computer/quinn/pull/346

**Review by flub — APPROVED** [review]
