### PR TITLE
fix(proto): set open path timer when first packet is sent

### LINKED ISSUE #456: PathOpen timer should be set only when the first packet for a path is sent
It is generally expected that queuing something and sending it happen extremely
close to each other, because the connection is correctly polled. If this does
not happen, however, the deadline for opening a path might be set too close to
the actual sending of the first packet (`PATH_CHALLENGE` at the moment of
writing). I've seen this happen in logs, where a path is added and has roughly
3s to get a path response, but the challenge is only sent 2.5s after it was
queued, leaving a very short window for responses and escentially no window for
retries. We need to fix the polling, yes, but local to the state of the
connetcion this is still a bug. The deadline should only be set once we have
sent something over the path.

### PR DESCRIPTION
**Pull request by divagant-martian**
## Description

Closes #456

## Breaking Changes

n/a

## Notes & open questions

While this helps mitigate a larger issue, this is still the correct approach.
We must base the time we give the remote to answer our PATH_CHALLENGE based on
when it was actually sent.

### CODE REVIEW

File: quinn-proto/src/connection/paths.rs [hunk 1]
```diff
@@ -212,12 +212,12 @@ pub(super) struct PathData {
     /// [`TransportParameters`]: crate::transport_parameters::TransportParameters
     pub(super) keep_alive: Option<Duration>,
 
-    /// Whether the path has already been considered opened from an application perspective
+    /// Whether the path has already been considered opened from an application perspective.
     ///
     /// This means, for paths other than the original [`PathId::ZERO`], a first path challenge has
     /// been responded to, regardless of the initial validation status of the path. This state is
     /// irreversible, since it's not affected by the path being closed.
```
Comment (flub) [inline quinn-proto/src/connection/paths.rs:219]: Whoa, this whole description does not match my multipath understanding of what an open path means. Perhaps we should also update it.

File: quinn-proto/src/connection/paths.rs [hunk 2]
```diff
@@ -608,6 +610,18 @@ pub(super) enum OnPathResponseReceived {
...
+pub(super) enum OpenStatus {
+    /// A first path challenge has not been sent.
+    #[default]
+    Pending,
+    /// The first path challenge has been sent on the wire.
+    Sent,
+    /// A response that validates this path has been received and the application has been
+    /// informed.
+    Informed,
+}
```
Comment (flub) [inline quinn-proto/src/connection/paths.rs:628]: I find this enum confusing, because it mixes validation state with openness. There already is a `PathData::validated` bool (which I think we all agree insufficiently describes the validation states). But at the moment open and validated are two orthogonal things to me.

File: quinn-proto/src/connection/mod.rs [hunk 3]
```diff
@@ -4942,7 +4934,7 @@ impl Connection {
                     let path = self.path_data_mut(path_id);
                     if network_path == path.network_path {
                         if let Some(updated) = path.update_observed_addr_report(observed)
-                            && path.open
+                            && path.open_status == paths::OpenStatus::Informed
```
Comment (flub) [inline quinn-proto/src/connection/mod.rs:4937]: Why does this even care at all whether this is open in any form? If we receive this frame and it is valid on this path ID than it should be reported, no?

File: quinn-proto/src/connection/mod.rs [hunk 4]
```diff
@@ -5665,6 +5657,15 @@ impl Connection {
             builder.write_frame(challenge, stats);
             builder.require_padding();
             let pto = self.ack_frequency.max_ack_delay_for_pto() + path.rtt.pto_base();
+            if path.open_status == paths::OpenStatus::Pending {
+                path.open_status = paths::OpenStatus::Sent;
+                self.timers.set(
+                    Timer::PerPath(path_id, PathTimer::PathOpen),
+                    now + 3 * pto,
+                    self.qlog.with_time(now),
+                );
```
Comment (flub) [inline quinn-proto/src/connection/mod.rs:5666]: Hum, I might be annoyingly brining this up again. But what if the packet opening the path does not include a PATH_CHALLENGE? I still think this will happen at some point.

I think the better place to set the timer is just below here, where there already is some other application logic: https://github.com/n0-computer/quinn/blob/6ec9ffec6a76e20f54018a498c376a265008985a/quinn-proto/src/connection/mod.rs#L1446

File: quinn-proto/src/connection/mod.rs (hunk 3 above)
Comment (divagant-martian) [reply quinn-proto/src/connection/mod.rs:4937]: this check is here because we often receive it before the event for path open has been emitted

File: quinn-proto/src/connection/paths.rs (hunk 1 above)
Comment (divagant-martian) [reply quinn-proto/src/connection/paths.rs:219]: This description is technically still correctly describing what we do. While we could make it more generic, we would be left without a proper explanation of the way things behave currently. The proper moment to update it is probably if we stop requiring a first path challenge

File: quinn-proto/src/connection/paths.rs (hunk 2 above)
Comment (divagant-martian) [reply quinn-proto/src/connection/paths.rs:628]: yes, that's true. Consequence of the way things currently work. This is already explained in the field, so we can be generic and refer to "first packet" here

File: quinn-proto/src/connection/mod.rs (hunk 3 above)
Comment (divagant-martian) [reply quinn-proto/src/connection/mod.rs:4937]: Also to note that this check is not new to this PR

File: quinn-proto/src/connection/mod.rs (hunk 4 above)
Comment (divagant-martian) [reply quinn-proto/src/connection/mod.rs:5666]: I agree with this change, but this changes logic that goes beyond this PR. IF we were to depend simply on a first ack, which I think it's a good idea, we would need to stop the timer appropriately. Changing this as you suggested, within this PR, leaves the timer in a potentially inconsistent state

File: quinn-proto/src/connection/paths.rs (hunk 1 above)
Comment (divagant-martian) [reply quinn-proto/src/connection/paths.rs:219]: Also note here that this is not a spec thing. The relevant part would be

> Whether the path has already been considered opened from an application perspective

which is an implementation decision

File: quinn-proto/src/connection/mod.rs (hunk 4 above)
Comment (matheus23) [reply quinn-proto/src/connection/mod.rs:5666]: Even if the packet opening a path is something else than the PATH_CHALLENGE, at the moment the `PathOpen` timer is strictly for handling the path challenge timing out, see also the code that it triggers (calling `path.data.reset_on_path_challenge()` and stopping the `PathChallengeLost` timer).

As diva says, it's fair to say that perhaps opening a path (on an already validated 4-tuple) could also be done without path challenges at all, but that'd require more changes to the path open timer to handle both the case where a path response vs. only an ACK opens the path.

And I think it's wise to go with the safer option for now.

File: quinn-proto/src/connection/mod.rs (hunk 3 above)
Comment (flub) [reply quinn-proto/src/connection/mod.rs:4937]: Yeah, I know it is not new. Does the user ever receive the observed address if this event is swallowed though?

Comment (flub) [reply quinn-proto/src/connection/mod.rs:4937]: asking not because it should be fixed here, but because we might have to open a new issue for it

File: quinn-proto/src/connection/mod.rs (hunk 4 above)
Comment (flub) [reply quinn-proto/src/connection/mod.rs:5666]: ooh, right. i now understand that the implications of what i was asking were bigger than i thought they were. ok, that's scope creep i guess.

File: quinn-proto/src/connection/mod.rs (hunk 3 above)
Comment (divagant-martian) [reply quinn-proto/src/connection/mod.rs:4937]: yes, this is sent here https://github.com/n0-computer/quinn/blob/6ec9ffec6a76e20f54018a498c376a265008985a/quinn-proto/src/connection/mod.rs#L4647-L4659
