### PR TITLE
fix: allow the remote to abandon paths even if no validated paths remain

### LINKED ISSUE #400: The connection is killed when the remote abandons the last validated path
We treat this as if the remote is abandoning the last path, for which the behaviour of killing the connection is acceptable. But this is not the last path, only the last validated path. The remote has no information about that state, which is local to the endpoint, nor is it expected to try to assume or figure it out. We need to "Accept" the abandon from a remote regardless of validation state. This issue is about the last _validated_ path. Related are:
- #399
- #398

### PR DESCRIPTION
**Pull request by divagant-martian**
## Description

Closes #400

Rejecting remotely intiated path abandons is not spec compliant, once a
`PATH_ABANDON` frame for a path is received it's considered as abandoned,
period. This fixes a bug where we would close the connection if the local
endpoint ends up with 0 validated paths, but open paths nonetheless.

## Breaking Changes

n/a

## Notes & open questions

See https://github.com/n0-computer/quinn/actions/runs/21615784338/ for the test in [5ac8360](https://github.com/n0-computer/quinn/pull/401/commits/5ac8360983351c985390f737bc88345c0c521212) failing

### CODE REVIEW

File: quinn-proto/src/connection/mod.rs
Comment (flub) [inline quinn-proto/src/connection/mod.rs:689]: We should probably add a note here to say that this will also refuse to close the path if that would leave no validated path open.

File: quinn-proto/src/tests/proptest.rs [hunk 1]
```diff
@@ -605,3 +605,31 @@ fn regression_there_should_be_at_least_one_path() {
...
     )));
 }
+
+/// Closing a path locally may be rejected if this leaves the endpoint without validated paths. For
+/// paths closed by the remote, however, a `PATH_ABANDON` frame must be accepted. In
+/// particular, it should not kill the connection.
+///
+/// This is a regression test.
+#[test]
+fn remote_can_close_last_validated_path() {
```
Comment (flub) [inline quinn-proto/src/tests/proptest.rs:615]: The convention seems to be to start regression tests with `regression_`, and I think this is a regression test?
