### PR TITLE
fix(proto): retry off-path NAT traversal probes and retire stale CIDs

### LINKED ISSUE #410: apply timers to off-path path challenges
The current PathChallengeLost (and related) only apply to on-path challenges.
Once #349 is solved, and for #364 to be completed, we need to handle timers for
off-path path challenges as well, an peruse use of the on-path timers to check
each kind applies to the right subset of sent challenges. Not doing so reduces
the effectiveness of probing alternate paths

### PR DESCRIPTION
**Pull request by dignifiedquire**
## Description

Off-path NAT traversal probes were fire-and-forget: sent once per address per round with no retry. This broke simultaneous-open NAT traversal because the first probe is typically dropped (the peer's NAT mapping doesn't exist yet when the probe arrives).

Now probes are retransmitted up to 10 times at initial-RTT PTO intervals, with fresh CIDs reserved for each attempt.

Fixes #410, relates to #376

## Changes

- `ServerState` tracks per-probe attempt count via `ProbeState`
- New `NatTraversalProbeRetry` connection timer fires at initial PTO-base intervals to re-queue probes
- Each probe reserves a fresh CID (no cross-path CID reuse)
- On new round, stale off-path challenges are cleared

## References

- [draft-seemann-quic-nat-traversal-02 §4](https://datatracker.ietf.org/doc/html/draft-seemann-quic-nat-traversal-02#section-4): Off-path challenges for NAT traversal
- [picoquic challenge retry in paths.c](https://github.com/private-octopus/picoquic/blob/master/picoquic/paths.c#L51): picoquic retries challenges up to `PICOQUIC_CHALLENGE_REPEAT_MAX` (3) attempts

## Notes

- If no reserved CIDs are available, the probe is skipped (not sent with the active CID)
- Retry timer uses PTO-base from initial RTT without max_ack_delay, since PATH_RESPONSE must be sent immediately

### CODE REVIEW

File: noq-proto/src/connection/send_buffer.rs [hunk 1]
```diff
@@ -585,9 +585,9 @@ mod tests {
 mod proptests {
     use super::*;
 
+    use crate::tests::subscribe;
```
Comment (divagant-martian) [inline noq-proto/src/connection/send_buffer.rs]: can we revert this random change please?

File: noq-proto/src/connection/paths.rs [hunk 2]
```diff
@@ -521,6 +521,17 @@ impl PathData {
         self.pending_on_path_challenge = false;
     }
 
+    /// Returns whether there are any pending off-path challenges.
+    pub(super) fn has_off_path_challenges(&self) -> bool {
+        !self.off_path_challenges_unconfirmed.is_empty()
+    }
+
+    /// Clears all off-path challenges (e.g. when a new NAT traversal round starts
+    /// and old probes are obsolete).
```
Comment (divagant-martian) [inline noq-proto/src/connection/paths.rs]: Because I know you will be asked this eventually, I'll go ahead and put it now: The docs should have a simple first line that describes what the method does, explanations later after a blank line. I'm not sure in theory which of all the guidelines we take direction from, but I found a few.

- [rustdoc component guidelines](https://doc.rust-lang.org/rustdoc/how-to-write-documentation.html#documenting-components)
- [rfc about api conventions](https://rust-lang.github.io/rfcs/0505-api-comment-conventions.html)
- [microsoft rust guidelines](https://microsoft.github.io/rust-guidelines/guidelines/docs/) yeah sure this is not the one, but anyhow

Basically please move the clarification to a sentence to the end, after a blank line 😅

File: noq-proto/src/connection/timer.rs [hunk 3]
```diff
@@ -32,16 +32,20 @@ pub(crate) enum ConnTimer {
     /// If no new path is opened before this fires, close the connection.
     /// See <https://www.ietf.org/archive/id/draft-ietf-quic-multipath-21.html#section-3.4-8>
     NoAvailablePath = 5,
+    /// When to retry off-path NAT traversal probes.
+    /// Fires once per PTO to retransmit probes that got no PATH_RESPONSE.
```
Comment (divagant-martian) [inline noq-proto/src/connection/timer.rs]:
```suggestion
    /// When to retry off-path NAT traversal probes.
    ///
    /// Fires once per PTO to retransmit probes that got no PATH_RESPONSE.
```

File: noq-proto/src/tests/encode_decode.rs [hunk 4]
```diff
@@ -1,6 +1,6 @@
 use bytes::{BufMut, BytesMut};
+use proptest::{prelude::*, prop_assert_ne};
```
Comment (divagant-martian) [inline noq-proto/src/tests/encode_decode.rs]: another one to revert

File: noq-proto/src/n0_nat_traversal.rs [hunk 5]
```diff
@@ -281,6 +281,20 @@ impl ClientState {
...
 
+/// Maximum number of times an off-path probe is sent before giving up.
+pub(crate) const MAX_OFF_PATH_PROBE_ATTEMPTS: u8 = 10;
+
+/// State of an off-path probe to a client address.
+#[derive(Debug)]
+pub(crate) struct ProbeState {
+    /// Number of times this probe has been sent (0 = not yet sent).
+    pub(crate) attempts: u8,
+    /// Whether this probe is ready to be picked up by `next_probe()`.
```
Comment (divagant-martian) [inline noq-proto/src/n0_nat_traversal.rs]:
```suggestion
    /// Whether this probe is ready to be picked up by [`ServerState::next_probe()`].
```

Comment (divagant-martian) [reply noq-proto/src/n0_nat_traversal.rs]: uhh this function is gone. This needs to reference something else

File: noq-proto/src/n0_nat_traversal.rs [hunk 6]
```diff
@@ -359,38 +380,69 @@ impl ServerState {
...
+            .find(|(_, state)| state.ready_to_send)
+            .map(|(addr, state)| ((*addr).into(), state.cid))
     }
 
-    pub(crate) fn remote(&self) -> SocketAddr {
-        self.remote.into()
+    /// Mark a probe as sent by address.
+    pub(crate) fn mark_probe_sent(&mut self, remote: IpPort, cid: ConnectionId) {
+        if let Some(state) = self.pending_probes.get_mut(&remote) {
+            if state.cid.is_none() {
```
Comment (divagant-martian) [inline noq-proto/src/n0_nat_traversal.rs]: I think we should update always. Whether the CID changes or not is not a concern of the nat traversal state and it shouldn't be as opinionated as this.

On the other hand, this can actually happen for reasons out of control of the nat traversal state, for example, if the path id that was used to send the og probe, that first CID is now retired. A retry would use another path id, which has its own set of CIDs and the one we should be using is that new one

File: noq-proto/src/connection/mod.rs [hunk 7]
```diff
@@ -2043,25 +2043,29 @@ impl Connection {
...
+        if !self.paths.get(&path_id)?.data.validated {
             return None;
         }
 
-        let cid = remote_cids.next_reserved()?;
-        let remote = probe.remote();
+        // Reuse the CID from the initial probe on retries (same address, RFC 9000 §9.5).
+        // On first send, reserve a fresh CID.
+        let cid = if let Some(prev) = prev_cid {
+            prev
```
Comment (divagant-martian) [inline noq-proto/src/connection/mod.rs]: ok this is very problematic and needs serious fixing. Let me explain:

- this method is for some path_id B received by param
- there is a prev CID ogCID that might have belonged to another path, let's say A
CIDs are used for routing, so when receiving the packet that contains this challenge on the other side, the remote will use ogCID to check what path it belongs to, it will find it belongs to A
- path id is used in the nonce calculation, so the remote will try decryption using a nonce computed based on A, and fail, because the one that was actually used was B
- we slowly but surely increase the count towards the keys limits and the connection could be dropped if we do this aggressively enough
- The idea is eventually to use the result of this to consider the path validated. The remote will never respond, because the packet couldn't even be decrypted
- be sad

Comment (dignifiedquire) [reply noq-proto/src/connection/mod.rs]: I have remove the reuse entirely for now, which should make it at least less broken 😅

File: noq-proto/src/tests/encode_decode.rs (hunk 4 above)
Comment (dignifiedquire) [reply noq-proto/src/tests/encode_decode.rs]: done

File: noq-proto/src/n0_nat_traversal.rs (hunk 6 above)
Comment (dignifiedquire) [reply noq-proto/src/n0_nat_traversal.rs]: done

File: noq-proto/src/connection/mod.rs [hunk 8]
```diff
@@ -2111,6 +2113,18 @@ impl Connection {
 
         path.record_path_challenge_sent(now, token, network_path);
 
+        // Set retry timer for off-path probes that got no PATH_RESPONSE.
+        if let Ok(server_state) = self.n0_nat_traversal.server_side_mut()
+            && server_state.has_pending_retries()
+        {
+            let pto = self.pto(SpaceKind::Data, path_id);
```
Comment (flub) [inline noq-proto/src/connection/mod.rs]: Using the on-path PTO here is strange. There's no reason at all that this is a relevant duration. It's the equivalent of making this a fairly random.

Probably better off using the PTO-base of the configured initial RTT?

File: noq-proto/src/connection/mod.rs [hunk 9]
```diff
@@ -2111,6 +2113,18 @@ impl Connection {
...
+            self.timers.set(
+                Timer::Conn(ConnTimer::OffPathProbeRetry),
```
Comment (flub) [inline noq-proto/src/connection/mod.rs]: Could we name this timer `NatTraverslaProbeRetry`? Off-path is going to confuse me at some point, since not all off-path probes are for nat traversal. But IIUC this timer is more specific than that.

Comment (dignifiedquire) [reply noq-proto/src/connection/mod.rs]: done

File: noq-proto/src/connection/mod.rs (hunk 8 above)
Comment (dignifiedquire) [reply noq-proto/src/connection/mod.rs]: changed, can you please check the initial one I am now using is calculated correctly?

File: noq-proto/src/connection/mod.rs [hunk 10]
```diff
@@ -2113,14 +2116,15 @@ impl Connection {
...
         path.record_path_challenge_sent(now, token, network_path);
 
-        // Set retry timer for off-path probes that got no PATH_RESPONSE.
+        // Set retry timer for NAT traversal probes that got no PATH_RESPONSE.
         if let Ok(server_state) = self.n0_nat_traversal.server_side_mut()
             && server_state.has_pending_retries()
         {
-            let pto = self.pto(SpaceKind::Data, path_id);
+            let initial_pto = RttEstimator::new(self.config.initial_rtt).pto_base()
+                + self.ack_frequency.max_ack_delay_for_pto();
```
Comment (flub) [inline noq-proto/src/connection/mod.rs]: You should not do the `+ max_ack_delay` since the probes must be responded to immediately.

```suggestion
            let initial_pto = RttEstimator::new(self.config.initial_rtt).pto_base();
```
