### PR TITLE
fix(proto): Avoid generating protocol violation errors in bad network conditions

### LINKED ISSUE #391: failing proptest: Interaction with involuntary connection migration can result in "peer failed to respond with PATH_ABANDON in time"
https://github.com/n0-computer/quinn/actions/runs/21523018733/job/62019155670

This is after the fixes that got in with #366

### PR DESCRIPTION
**Pull request by matheus23**
## Description

This PR changes the way the path closing state machine works.
Previously
1. we generated protocol violation errors when the other side still sends to a path we abandoned after a timeout
2. we immediately sent a MAX_PATH_ID frame after abandoning a path locally.

We needed (1) because otherwise it's possible the client just keeps opening new paths, causing us to accumulate memory, without us being able to free said memory, by delaying responding to PATH_ABANDONs indefinitely.

This PR changes (2) to enable removing (1): By delaying MAX_PATH_ID until all prerequisites for throwing away the path state are fulfilled, we aren't susceptible to the client tricking us into closing many paths, as the client will quickly hit MAX_PATH_ID limits without responding to the server's PATH_ABANDON frames.

Crucially, we also don't start discarding paths at all until we received a PATH_ABANDON from the other side.

## Notes

An alternative to #434 that doesn't look at ACKs.

Closes #391

### CODE REVIEW

File: quinn-proto/src/tests/proptest.rs [hunk 1]
```diff
@@ -721,3 +721,63 @@ fn regression_there_should_be_at_least_one_path() {
...
+/// Yet another regression with PATH_ABANDON "not being answered" by our peer.
+///
+/// This test ended up severing the connection in an interesting way: It generates
+/// a passive migration just before closing the path. The passive migration breaks
+/// path 0 (which would usually be the (1.1.1.0, 2.2.2.0) tuple, the client "migrated"
+/// to (1.1.1.1, 2.2.2.0) without the server knowing that).
+/// This means that path 0 is effectively broken, but the server still has path 0
+/// verified.
+/// When the server then wants to abandon path 1, it chooses path 0 as the path to
+/// send the path abandon on, even though that path is "doomed forever".
```
Comment (flub) [inline quinn-proto/src/tests/proptest.rs:736]: In this scenario the client's path 0 address is quietly changed by a middlebox. But the client does not choose to send on path 0 so the server never sees the passive migration, is that correct? Because if the client would send something on path 0 then the server should validate the migration and everything would work.

The way this is phrased does not make this clear to me, my first version of the comment was saying that this should work really. Could you improve the wording?

File: quinn-proto/src/connection/mod.rs [hunk 2]
```diff
@@ -5880,11 +5859,9 @@ impl Connection {
                     // still be packets incoming on the path at that point.
                     // This timer will actually get reset to a value that's likely to be even earlier
                     // once we actually receive the PATH_ABANDON frame itself.
-                    let abandoned_pto =
-                        self.paths.get(&path_id).unwrap().data.rtt.pto_base() + ack_delay;
                     self.timers.set(
                         Timer::PerPath(abandoned_path_id, PathTimer::DiscardPath),
-                        now + 3 * send_pto + 3 * abandoned_pto,
+                        now + 3 * send_pto,
```
Comment (Frando) [inline quinn-proto/src/connection/mod.rs]: The comment above these lines still details why this timer is set to `3 * send_pto + 3 * abandon_pto`. Is it correct to reduce from ~6xPTO to 3xPTO here?

Comment (matheus23) [reply quinn-proto/src/connection/mod.rs]: Right. I need to update the comment, thank you.
Yeah - the reduction here is intentional. The spec requires at least 3 * PTO for us before discarding path state.
We used to have two phases - thus it was this combination of PTOs. Now it's just one phase: Send PATH_ABANDON, abandon the path after some time.

File: quinn-proto/src/tests/proptest.rs (hunk 1 above)
Comment (matheus23) [reply quinn-proto/src/tests/proptest.rs:736]: > In this scenario the client's path 0 address is quietly changed by a middlebox. But the client does not choose to send on path 0 so the server never sees the passive migration, is that correct? Because if the client would send something on path 0 then the server should validate the migration and everything would work.

Yes

I'll improve the wording. My writing-comments ability yesterday wasn't really there :sweat_smile:
