### PR TITLE
fix! make `Path::close` completely sync (this never returned in the happy case)

### LINKED ISSUE #418: PathEvent::Closed is never emitted

### PR DESCRIPTION
**Pull request by divagant-martian**
## Description

Closes #418

The pubcli Api `Path::close` depends on the event `PathEvent::Closed` being
emitted. This was never the case, so application callers never actually got
access to the error. There were two options here, fixing this and emitting the
event, or removing it.

I opted for removal because the fact that the path state is kept for some time,
and that this is different from closing the path, is very low into the lore of
multipath and does not really provide the user any useful information. Second
argument is that this seems like it was never actually used, as no users have
complained about this broken api. Users that used this call can relly on events
to know when the path has been closed.

In the unexpecte (to me) case that this API is restored, we should do so using
the `Abandoned` event instead. I don't think we should do this unless we find
an use case in which this api, vs events is meaningully more convenient or
useful.

A test is added for the basic functionality of `Path::close`

## Breaking Changes

- `PathEvent::Closed` in `proto` has been removed. Use `PathEvent::Abandoned`
  instead.
- `Path::close` in `quinn` no longer has a return value other than `()`, to
  know when a path has been closed use the events api instead.
- `ClosePath` is gone. Refer to the above item

## Notes & open questions

n/a

### CODE REVIEW

File: quinn-proto/src/connection/paths.rs [hunk 1]
```diff
@@ -910,18 +910,7 @@ pub enum PathEvent {
...
-        /// Error code supplied by the peer
-        /// See <https://www.ietf.org/archive/id/draft-ietf-quic-multipath-14.html#name-error-codes>
-        /// for a list of known errors.
-        error_code: VarInt,
-    },
-    /// All remaining state for a path has been removed
-    ///
-    /// The [`PathEvent::Closed`] would have been emitted for this path earlier.
+    /// The path was abandoned and all remaining state for it has been removed.
     Abandoned {
```
Comment (flub) [inline quinn-proto/src/connection/paths.rs:914]: Can we take the opportunity to rename this event `Discarded` instead?

I would expect an `Abandoned` event to tell me when the path is being abandoned, which this isn't AFAIK.

Comment (flub) [reply quinn-proto/src/connection/paths.rs:914]: hum, I guess this doesn't really belong in a `fix` PR...
