### PR TITLE
fix(quinn-proto): path abandon does not clear all timers, in particular, not loss detection

### LINKED ISSUE #435: bug: packets that have not been acked but not yet deemed lost for an abandoned path are not retransmitted
This was diagnosed because a PATH_ABANDON was not retransmitted. The scenario was this:

PATH_ABANDON 3 is sent on path 7
The loss timer for path 7 is armed
Path 7 is abandoned, all path timers are cleared
PATH_ABANDON 3 is not re-sent because there's no loss timer that's triggered

This applies to any packet and frames, not just PATH_ABANDON, but given this
frame is crucial for multipath, this is generating a lot of issues

cc @matheus23 with whom we diagnosed this

### PR DESCRIPTION
**Pull request by divagant-martian**
## Description

Closes #435

The `LossDetection` timer should not be cleared once the path is closed.

## Breaking Changes

n/a

## Notes & open questions

n/a

### CODE REVIEW

File: quinn-proto/src/connection/mod.rs [hunk 1]
```diff
@@ -739,10 +739,39 @@ impl Connection {
...
+        for timer in timer::PathTimer::VALUES {
+            // match for completeness
+            let keep_timer = match timer {
+                // These timers deal with sending and receiving PATH_CHALLENGE and
+                // PATH_RESPONSE, but now that the path is abandoned, we no longer care about
+                // these frames or their timing
+                PathTimer::PathValidation | PathTimer::PathChallengeLost | PathTimer::PathOpen => {
+                    false
+                }
+                // These timers deal with the lifetim of the path. Now that the path is abandoned,
```
Comment (matheus23) [inline quinn-proto/src/connection/mod.rs]:
```suggestion
                // These timers deal with the lifetime of the path. Now that the path is abandoned,
```

File: quinn-proto/src/connection/mod.rs [hunk 2]
```diff
@@ -739,10 +739,39 @@ impl Connection {
...
+                // these are not relevant.
+                PathTimer::PathKeepAlive => false,
+                PathTimer::PathIdle => false,
```
Comment (matheus23) [inline quinn-proto/src/connection/mod.rs]:
```suggestion
                PathTimer::PathKeepAlive | PathTimer::PathIdle=> false,
```

File: quinn-proto/src/connection/mod.rs [hunk 3]
```diff
@@ -739,10 +739,39 @@ impl Connection {
...
+                // Sent packets still need to be identified as lost to trigger timely
+                // retransmission.
+                PathTimer::LossDetection => true,
+                // This path should not be used for sending after the PATH_ABANDON frame is sent.
+                // However, any outstanding data that should be sent before PATH_ABANDON, should
+                // still respect pacing.
+                PathTimer::Pacing => true,
+            };
+
+            if !keep_timer {
```
Comment (matheus23) [inline quinn-proto/src/connection/mod.rs:777]: Minor nit: Perhaps flipping the boolean to `clear_timer` is more readable. (Fewer negations)

Comment (divagant-martian) [reply quinn-proto/src/connection/mod.rs:777]: I had initially writen this as "stop_timer" but realized I kept writing the inverse. Doing this as stop, at least the way my brain decided to tackle this, is what felt as a double negative. If you check the comments, what I'm explaining is do we care or we not care. Going back to stopping means explaining if it most be removed or not. This are logically the same but removing the timer is understood on itself as a negative.

I probably failed at explaining myself but my point here is: you all found this logic understandable, and I've seen the alternative to be less understandable. The current form of this is intentional, so I'll leave the code as is
