### PR TITLE
fix(proto): handle duplicated reach out frames

### LINKED ISSUE #429: bug: "PTO expired while unset"/protocol violation "tried to add too many addresses to their advertised set"
Originally reported to sentry: https://number0.sentry.io/issues/7267115868

Diva is already investigating this & potentially has a fix, [see discord](https://discord.com/channels/949724860232392765/1472872356555919473).

### PR DESCRIPTION
**Pull request by divagant-martian**
## Description

Closes #429

This error is returned when the client sends more addresses than allowed in
`REACH_OUT` frames. But this could be triggered if the client re-transmitted a
frame as well, which of course is not a protocol violation. This PR improves
handling duplicated `REACH_OUT` frames both on the sending and receiving side.

## Breaking Changes

n/a

## Notes & open questions

n/a

### CODE REVIEW

File: quinn-proto/src/connection/mod.rs [hunk 1]
```diff
@@ -5602,12 +5602,13 @@ impl Connection {
...
         {
-            while let Some(local_addr) = addresses.pop() {
+            while let Some(local_addr) = addresses.iter().next().copied() {
+                let local_addr = addresses.take(&local_addr).expect("found from iter");
                 let reach_out = frame::ReachOut::new(*round, local_addr);
                 if builder.frame_space_remaining() > reach_out.size() {
                     builder.write_frame(reach_out, stats);
                 } else {
-                    addresses.push(local_addr);
+                    addresses.insert(local_addr);
```
Comment (flub) [inline quinn-proto/src/connection/mod.rs:5611]: Not actually this PR, though I noticed that if you e.g. don't have space to write an IPv6 frame, you might still be able to write an IPv4 frame. Yet this bails out of the loop right away. Do you think this is worth addressing?

**Review by flub — APPROVED** [review]
