### PR TITLE
fix(proto): Check `abandoned_paths` in `open_path_ensure`

### LINKED ISSUE #316: open_path_ensure does not open a new path if 4-tuple is abandoned but still has state
Holepunching somehow ends up calling `Connection::open_path_ensure` for each remote for which it wants to holepunch. That function however searches for a path with a 4-tuple match in `Connection::paths`, and if such a path exists it does not open a new path but just returns that `PathId`.

However this means that if a path was recently abandoned the `PathData` for it still exists, as this is kept around for a little while. And open_path_ensure will not attempt to open this path again.

This matters because a round could have been very short: e.g. if a new round was already initiated by the application there might not have been time to get the path validated. And starting a new round currently abandons all paths involved in the previous round that have not yet been path-validated.

### PR DESCRIPTION
**Pull request by matheus23**
## Description

Closes #316 

## Notes & open questions

Good find @flub!

### CODE REVIEW

File: quinn-proto/src/connection/mod.rs [hunk 1]
```diff
@@ -569,16 +569,13 @@ impl Connection {
...
-                .find(|(_id, path)| network_path.is_probably_same_path(&path.data.network_path))
-            {
-                Some((path_id, _state)) => (*path_id, true),
-                None => (self.open_path(network_path, initial_status, now)?, false),
-            },
-        )
+        match self.paths.iter().find(|(id, path)| {
+            network_path.is_probably_same_path(&path.data.network_path)
+                && !self.abandoned_paths.contains(*id)
+        }) {
```
Comment (dignifiedquire) [inline quinn-proto/src/connection/mod.rs]: this is becoming very long, maybe put this into its own expression/line
