### PR TITLE
fix(proto): Properly separate on-path and off-path challenge logic

### LINKED ISSUE #447: fix: Don't clear off-path path challenges when path validation during migration fails
https://github.com/n0-computer/quinn/pull/443#discussion_r2835362179

### PR DESCRIPTION
**Pull request by matheus23**
## Description

This PR separates on-path and off-path challenge code.
- `send_new_challenge` always sends on-path challenges, so it's renamed to `tx_queue_on_path_challenge`
- `reset_challenges` is meant for resetting on-path challenges (on-path validation timing out shouldn't reset off-path challenges?) so it's renamed to `reset_on_path_challenges`
- `earliest_expiring_challenge` is meant only for on-path challenges, as we have no mechanism for re-sending off-path challenges! Previously, this would cause expired off-path challenges to be resent as *on-path* challenges (via `send_new_challenge` being set after the challenge lost timer for *an off-path challenge* would expire). This doesn't make sense, so instead I changed its behavior and renamed it to `earliest_expiring_on_path_challenge`.
- Also renames `PathData::new_path_challenge` to `PathData::record_path_challenge_sent`, as I would expect a function called `new_path_challenge` to return something.

Fixes #447 

## Notes & open questions

We should find a way of properly resending off-path path challenges, but right now we don't have a mechanism, so this just fixes the broken behavior.

### CODE REVIEW

File: quinn-proto/src/connection/paths.rs [hunk 1]
```diff
@@ -152,7 +152,11 @@ pub(super) struct PathData {
     /// Whether to *immediately* trigger another PATH_CHALLENGE.
     ///
     /// This is picked up by [`super::Connection::space_can_send`].
-    pub(super) send_new_challenge: bool,
+    ///
+    /// Only used for RFC9000-style path migration and multipath path validation (for opening).
+    ///
+    /// This is **not used** for n0 nat traversal challenge sending.
+    pub(super) send_new_on_path_challenge: bool,
```
Comment (flub) [inline quinn-proto/src/connection/paths.rs]: I would really like this to be named `pending_on_path_challenge`. To me `pending` is the convention most of the code uses to signal that this is data that should result in a frame being sent next time poll_transmit is called. So I do think that would be more consistent.

File: quinn-proto/src/connection/paths.rs [hunk 2]
```diff
@@ -363,7 +367,12 @@ impl PathData {
         }
     }
 
-    pub(super) fn new_path_challenge(&mut self, now: Instant, token: u64, network_path: FourTuple) {
+    pub(super) fn record_path_challenge_sent(
+        &mut self,
+        now: Instant,
+        token: u64,
+        network_path: FourTuple,
+    ) {
```
Comment (flub) [inline quinn-proto/src/connection/paths.rs:375]: eh, good rename. i actually misread what this did in the other pr...

File: quinn-proto/src/connection/paths.rs (hunk 1 above)
Comment (divagant-martian) [reply quinn-proto/src/connection/paths.rs]: Just mentioning that this used to be called that, and we renamed it because it was very confusing. Maybe it's less confusing now that the field actually has docs (all these docs were added by our team) I'm fine with whatever you two decide

File: quinn-proto/src/connection/mod.rs [hunk 3]
```diff
@@ -4709,20 +4709,11 @@ impl Connection {
...
-                            let next_challenge = path
-                                .data
-                                .earliest_expiring_challenge()
-                                .map(|time| time + self.ack_frequency.max_ack_delay_for_pto());
-                            self.timers.set_or_stop(
-                                Timer::PerPath(path_id, PathChallengeLost),
-                                next_challenge,
-                                self.qlog.with_time(now),
-                            );
+                            debug!("Valid response to off-path PATH_CHALLENGE");
```
Comment (divagant-martian) [inline quinn-proto/src/connection/mod.rs]: could you log the frame here?
```suggestion
                            debug!(%response, "Valid response to off-path PATH_CHALLENGE");
```

File: quinn-proto/src/connection/timer.rs [hunk 4]
```diff
@@ -47,7 +47,7 @@ pub(crate) enum PathTimer {
     PathIdle = 1,
     /// When to give up on validating a new path from RFC9000 migration
     PathValidation = 2,
-    /// When to resend a path challenge deemed lost
+    /// When to resend an on-path path challenge deemed lost
```
Comment (divagant-martian) [inline quinn-proto/src/connection/timer.rs:50]:
```suggestion
    /// When to resend an on-path path challenge deemed lost.
```

File: quinn-proto/src/connection/paths.rs (hunk 1 above)
Comment (matheus23) [reply quinn-proto/src/connection/paths.rs]: We discussed this in discord and decided on `tx_queue_on_path_challenge`.

File: quinn-proto/src/connection/timer.rs (hunk 4 above)
Comment (matheus23) [reply quinn-proto/src/connection/timer.rs:50]: Eh - I don't think I'm going to add that dot :sweat_smile: 

All other comments on the same enum are not yet dottified - someone else can do this :P
