### PR TITLE
fix: Do not send off-path data when closing

### LINKED ISSUE #357: Sending CONNECTION_CLOSE frames
We have a bug where we might be sending too much at connection close time. At the same time we should be careful of an on-path attacker spoofing a connection migration.

See https://github.com/n0-computer/quinn/pull/231#discussion_r2713975358

### PR DESCRIPTION
**Pull request by flub**
## Description

When we are closing we're only supposed to send packets containing
CONNECTION_CLOSE and (PATH_)ACK frames. There is no need to continue
sending any off-path data.

We do have the option of sending a CONNECTION_CLOSE to the new
remote if we get an involuntary migration during close. But we'd
have to make sure not to exceed the anti-amplification limit
since we can no longer validate the path.

We are also allowed to simply discard packets from a migrated
peer during the closing state. Which is what we do.

## Breaking Changes

n/a

## Notes & open questions

Closes #357 

Note that the base is #338. I won't merge before that is merged so
it shows up as a separate commit because this was a pre-existing
bug.

### CODE REVIEW

File: quinn-proto/src/connection/mod.rs [hunk 1]
```diff
@@ -1086,7 +1086,9 @@ impl Connection {
         let mut congestion_blocked = false;
 
         for &path_id in &path_ids {
-            if let Some(transmit) = self.poll_transmit_off_path(now, buf, path_id) {
+            if let Some(transmit) = self.poll_transmit_off_path(now, buf, path_id)
```
Comment (divagant-martian) [inline quinn-proto/src/connection/mod.rs]: I know you love if-let chains but this will pollute the buffer if the conditional prevents this from being sent. The conditional needs to be first

File: quinn-proto/src/connection/mod.rs [hunk 2]
```diff
@@ -1086,8 +1086,8 @@ impl Connection {
         let mut congestion_blocked = false;
 
         for &path_id in &path_ids {
-            if let Some(transmit) =
-                self.poll_transmit_off_path(now, buf, path_id, connection_close_pending)
+            if let Some(transmit) = self.poll_transmit_off_path(now, buf, path_id)
+                && !connection_close_pending
```
Comment (matheus23) [inline quinn-proto/src/connection/mod.rs]:
```suggestion
            if !connection_close_pending
                && let Some(transmit) = self.poll_transmit_off_path(now, buf, path_id)
```

File: quinn-proto/src/connection/mod.rs (hunk 1 above)
Comment (flub) [reply quinn-proto/src/connection/mod.rs]: :scream: thanks for catching this. And thanks to @matheus23 for the fix.
